# Generated by Django 4.0.6 on 2022-07-19 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')])),
                ('confirm_password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')])),
                ('mobile_phone', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='accounts')),
                ('is_active', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(choices=[('cairo', 'cairo'), ('alex', 'alex'), ('aswan', 'aswan'), ('giza', 'giza'), ('sohage', 'sohage'), ('assuit', 'assuit'), ('6october', '6october'), ('10ramadan', '10ramadan'), ('qena', 'qena'), ('luxor', 'luxor'), ('menia', 'menia'), ('sena', 'sena'), ('sharqia', 'sharqia'), ('iesmalia', 'iesmalia'), ('tanta', 'tanta'), ('matrouh', 'matrouh'), ('dahab', 'dahab')], max_length=50, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
