# Generated by Django 4.0.6 on 2022-07-10 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')])),
                ('confirm_password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')])),
                ('mobile_phone', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(8, 'the field must contain at least 8 characters')])),
                ('image', models.ImageField(upload_to='meida/accounts')),
            ],
        ),
    ]
