# Generated by Django 4.0.6 on 2022-07-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_phone',
            field=models.IntegerField(),
        ),
    ]
