# Generated by Django 4.0.6 on 2022-07-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(upload_to='accounts'),
        ),
    ]
