# Generated by Django 4.0.6 on 2022-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_username_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_phone',
            field=models.CharField(max_length=11),
        ),
    ]
