# Generated by Django 4.0.6 on 2022-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_active_account_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
