# Generated by Django 4.0.6 on 2022-07-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_is_active_remove_account_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
