# Generated by Django 4.0.6 on 2022-07-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_is_active_account_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
