# Generated by Django 4.0.6 on 2022-07-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(choices=[('cairo', 'cairo'), ('alex', 'alex'), ('aswan', 'aswan'), ('giza', 'giza'), ('sohage', 'sohage'), ('assuit', 'assuit'), ('6october', '6october'), ('10ramadan', '10ramadan'), ('qena', 'qena'), ('luxor', 'luxor'), ('menia', 'menia'), ('sena', 'sena'), ('sharqia', 'sharqia'), ('iesmalia', 'iesmalia'), ('tanta', 'tanta'), ('matrouh', 'matrouh'), ('dahab', 'dahab')], max_length=50)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
