# Generated by Django 4.0.6 on 2022-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('cairo', 'cairo'), ('alex', 'alex'), ('aswan', 'aswan'), ('giza', 'giza'), ('sohage', 'sohage'), ('assuit', 'assuit'), ('6october', '6october'), ('10ramadan', '10ramadan'), ('qena', 'qena'), ('luxor', 'luxor'), ('menia', 'menia'), ('sena', 'sena'), ('sharqia', 'sharqia'), ('iesmalia', 'iesmalia'), ('tanta', 'tanta'), ('matrouh', 'matrouh'), ('dahab', 'dahab')], max_length=50, null=True),
        ),
    ]
