# Generated by Django 4.0.6 on 2022-07-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_alter_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=20)),
                ('details', models.TextField(max_length=300)),
                ('category', models.CharField(choices=[('hospital', 'hospital'), ('school', 'school'), ('weeding', 'weeding'), ('masjid', 'masjid'), ('water', 'hospital'), ('hayaat karima', 'hayaat karima')], max_length=20)),
                ('total_target', models.CharField(max_length=20)),
                ('end_date', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teg', models.CharField(max_length=20)),
                ('project_name_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectfund.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectfund.project')),
            ],
        ),
    ]
