# Generated by Django 4.0.6 on 2022-07-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('details', models.TextField(max_length=300)),
                ('category', models.CharField(choices=[('hospital', 'hospital'), ('Michael', 'Michael'), ('education', 'education'), ('Corona', 'Corona'), ('EMERGENCY', 'EMERGENCY')], max_length=20)),
                ('total_target', models.CharField(max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('donations', models.CharField(default=0, max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('report', models.ManyToManyField(related_name='project_report', to='account.account')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('ratee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='projectfund.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('project_name_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectfund.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectfund.project')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_account_project', models.CharField(default=0, max_length=20)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectfund.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projectfund.project')),
                ('report', models.ManyToManyField(related_name='c_project_report', to='account.account')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
