# Generated by Django 4.0.6 on 2022-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
