# Generated by Django 4.0.6 on 2022-07-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_token'),
        ('projectfund', '0002_project_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_account_project', models.CharField(default=0, max_length=20)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectfund.project')),
            ],
        ),
    ]
