# Generated by Django 4.0.6 on 2022-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfund', '0003_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('hospital', 'hospital'), ('Michael', 'Michael'), ('education', 'education'), ('Corona', 'Corona'), ('hayaat karima', 'hayaat karima')], max_length=20),
        ),
    ]
