# Generated by Django 4.0.6 on 2022-07-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectfund', '0004_alter_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttag',
            old_name='teg',
            new_name='tag',
        ),
    ]
