# Generated by Django 4.0.6 on 2022-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_country'),
        ('projectfund', '0005_rename_teg_projecttag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report',
            field=models.ManyToManyField(related_name='project_report', to='account.account'),
        ),
    ]
