# Generated by Django 4.0.6 on 2022-07-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_country'),
        ('projectfund', '0006_project_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AddField(
            model_name='project',
            name='donations',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('ratee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='projectfund.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projectfund.project')),
                ('report', models.ManyToManyField(related_name='c_project_report', to='account.account')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
