# Generated by Django 4.0.6 on 2022-07-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20220718_2015'),
        ('projectfund', '0007_alter_project_options_project_donations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('hospital', 'hospital'), ('Michael', 'Michael'), ('education', 'education'), ('Corona', 'Corona'), ('EMERGENCY', 'EMERGENCY')], max_length=20),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_account_project', models.CharField(default=0, max_length=20)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectfund.project')),
            ],
        ),
    ]
